#!/bin/bash -x

SRC_DIR=$1 #  root folder of the workspace, /opt/git/workspace
BUILD_DIR=$2 # /mnt/deb-builds/${PACKAGE_NAME}-${VERSION}
PACKAGE_NAME=$3 # appName
VERSION=$4 # autogenerated timestamp
echo "Using package ${PACKAGE_NAME} and version ${VERSION}"

# create package contents in build directory
rsync -a ${SRC_DIR}/* ${BUILD_DIR}/src/
echo "${VERSION}" > ${BUILD_DIR}/version_num

# Specifying environment variables for compose
# Values present in the environment at runtime will always override
# those defined inside the .env file.
# Similarly, values passed via command-line arguments
# take precedence as well.
# Environment variables defined in the .env file
# are not automatically visible inside containers.

#creating the docker-compose .env for this package
cat << EOENV > ${BUILD_DIR}/src/.env
# Generated by package.sh for package ${PACKAGE_NAME} version ${VERSION}
SGK_APP=${SGK_APP}
SGK_DEPLOY_ID=${SGK_DEPLOY_ID}
SGK_BASE_DOMAIN=${SGK_BASE_DOMAIN}
SGK_ENVIRONMENT=${SGK_ENVIRONMENT}
EOENV

echo "Contents of generated .env:"
cat ${BUILD_DIR}/src/.env
echo "End of generated .env"

mkdir -p ${BUILD_DIR}/DEBIAN

# creating the main control file for this package
### NOTE PRE-DEPENDS!!! This package will FAIL without it.
cat << EOF > ${BUILD_DIR}/DEBIAN/control
Package: $PACKAGE_NAME
Version: $VERSION
Maintainer: ITHAKA <support@ithaka.org>
Architecture: amd64
Section: main
Priority: optional
Depends: aufs-tools, linux-image-extra-$(uname -r), linux-image-extra-virtual, libsystemd-journal0
Description: Sample Docker via debian package installed through Sagoku
EOF

# creating the post-install script for this package
cat << EOPOST > ${BUILD_DIR}/DEBIAN/postinst
#!/bin/bash
set -x
logger "Running postinstall setup for package $PACKAGE_NAME and version ${VERSION}"

/src/setup.sh
EOPOST
chmod 0755 ${BUILD_DIR}/DEBIAN/*inst
